# Generated by Django 5.2.7 on 2025-11-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.CharField(default='', help_text='Comma-separated product IDs', max_length=255),
            preserve_default=False,
        ),
    ]
